Repository EmbeddedLLM/embeddedllm, pull requests merged in 2024-08, with the labels that each got.

#16 [BUG] Verify v0.2 IPEX-LLM Support and Hotfix
  ellm_api_server.spec
  setup.py
  src/embeddedllm/entrypoints/api_server.py
  src/embeddedllm/version.py
Labels: type: bug

#25 Autoload + onnx model and ipexllm in the model ui
  README.md
  docs/model/onnxruntime_cpu_models.md
  docs/model/onnxruntime_directml_models.md
  docs/model/onnxruntime_models.md
  src/embeddedllm/backend/onnxruntime_engine.py
  src/embeddedllm/engine.py
  src/embeddedllm/entrypoints/api_server.py
  src/embeddedllm/entrypoints/modelui.py
  src/embeddedllm/inputs.py
Labels: priority: high, type: documentation, type: enhancement / feature

#26 Update openvino in modelui model list
  README.md
  docs/model/ipex_models.md
  docs/model/openvino_models.md
  src/embeddedllm/engine.py
  src/embeddedllm/entrypoints/modelui.py
Labels: type: documentation, type: enhancement / feature
