Repository EmbeddedLLM/embeddedllm, pull requests merged in 2024-09, with the labels that each got.

#33 Added OpenVINO vision model support
  src/embeddedllm/backend/onnxruntime_engine.py
  src/embeddedllm/backend/openvino_engine.py
  src/embeddedllm/backend/ov_phi3_vision.py
Labels: type: enhancement / feature

#36 [BUG FIXED] Update gradio version in requirements-webui.txt
  requirements-webui.txt
Labels: type: bug

#38 Fix ipex installation dependencies
  README.md
  requirements-ipex.txt
  setup.py
Labels: type: bug

#42 Update the `requirements-directml.txt` to the latest version
  README.md
  requirements-directml.txt
Labels: type: enhancement / feature

#44 [BUG] Fix pydantic bug which causes the PyInstaller Binary to fail to run
  requirements-common.txt
  src/embeddedllm/version.py
Labels: priority: critical, type: bug
